---
apiVersion: V1
kind: ReplicationController
metadata:
  name: domain1
spec:
  replicas: 3
  selector:
    app: weblogic-domain1
  template:
    metadata:
      labels:
        app: weblogic-domain1
    spec:
      containers:
        -
          image: "punitporwal07/weblogic1036:191004"
          name: wls1036
          ports:
            -
              containerPort: 61000-61006
